name: CI/CD for Python Setuptools Project

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            run-ci:
                description: "Run CI"
                required: true
                default: "false"

jobs:
    build:
        if: github.event.inputs.run-ci == 'true' || github.event_name != 'workflow_dispatch'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true

            - name: Run cargo check
              uses: actions-rs/cargo@v1
              with:
                  command: check

            - name: Install Maturin
              run: pip install maturin

            - name: Build and develop the Rust package
              run: maturin develop
              working-directory: fhe_http_python/fhe

            - name: Install dependencies
              run: pip install -r fhe_http_python/requirements.txt

            - name: Install the package
              run: pip install .

    version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Bump version
              run: |
                  current_version=$(grep -Po '(?<=version=)\d+\.\d+\.\d+' fhe_http_python/setup.py)
                  new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++;print}')
                  sed -i "s/version=\"$current_version\"/version=\"$new_version\"/" fhe_http_python/setup.py
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git commit -am "Bump version to $new_version"
                  git tag "v$new_version"
                  git push origin --tags
                  git push origin HEAD:main
